version: "3.7"
services:
  clef:
    build:
      context: .
      dockerfile: clef.dockerfile
    networks:
      - truebit-net
    env_file:
      - .env
    ports:
      - 8550:8550
    volumes:
      - ./docker/clef:/home/truebit
    restart: always
  geth:
    image: ethereum/client-go:stable
    depends_on:
      clef:
        condition: service_healthy
      ipfs:
        condition: service_healthy
    # For access to geth from host-OS
    # 1. Uncomment ports mapping
    # 2. Replace "--http.vhosts='geth'" with --http.vhosts='*'
    # Note that this expose your geth instance
    #ports:
    #  - 8545:8545
    networks:
      - truebit-net
    command: "--nousb --goerli --syncmode=light --signer='http://clef:8550' --ipcdisable --http.addr=0.0.0.0 --http --http.vhosts='geth,localhost'"
    healthcheck:
      test: 'wget --no-verbose --tries=1 --spider http://geth:8545'
    volumes:
      - ./docker/geth/.ethereum:/root/.ethereum
    restart: always
  ipfs:
    build:
      context: .
      dockerfile: ipfs.dockerfile
    networks:
      - truebit-net
    ports:
      - 4001:4001
      - 5001:5001
      - 8080:8080
    volumes:
      - ./docker/ipfs/export:/export
      - ./docker/ipfs/export:/data/ipfs
      - ./docker/ipfs/.ipfs:/root/.ipfs
    restart: always
  os:
    build:
      context: .
      dockerfile: truebit-os.dockerfile
    depends_on:
      geth:
        condition: service_healthy
    volumes:
      - ./docker/truebit-os:/truebit-eth/logs
    env_file:
      - .env
    networks:
      - truebit-net
    restart: always

  truebit-toolchain:
    build:
      context: .
      dockerfile: wasm.dockerfile
    networks:
      - truebit-net
    env_file:
      - .env

  sample_tasks:
    build:
      context: .
      dockerfile: samples-legacy.dockerfile

networks:
  truebit-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16