version: "3"
services:
  clef:
    build:
      context: .
      dockerfile: clef.dockerfile
    networks:
      - truebit-net
    env_file:
      - .env
    ports:
      - 8550:8550
    volumes:
      - ./docker/clef:/home/truebit
  geth:
    image: ethereum/client-go:stable
    depends_on:
      clef:
        condition: service_healthy
      ipfs:
        condition: service_healthy
    ports:
      - 8545:8545
    networks:
      - truebit-net
    command: "--nousb --goerli --syncmode=light --signer='http://clef:8550' --http.addr=0.0.0.0 --http --http.vhosts=*"
    healthcheck:
      test: 'wget --no-verbose --tries=1 --spider http://localhost:8545'
    volumes:
      - ./docker/geth/.ethereum:/root/.ethereum
  ipfs:
    build:
      context: .
      dockerfile: ipfs.dockerfile
    networks:
      - truebit-net
    ports:
      - 4001:4001
      - 5001:5001
      - 8080:8080
    volumes:
      - ./docker/ipfs/export:/export
      - ./docker/ipfs/export:/data/ipfs
      - ./docker/ipfs/.ipfs:/root/.ipfs
  os:
    build:
      context: .
      dockerfile: truebit-os.dockerfile
    depends_on:
      geth:
        condition: service_healthy
    volumes:
      - ./docker/truebit-os:/truebit-eth/logs
    env_file:
      - .env
    networks:
      - truebit-net

  truebit-toolchain:
    build:
      context: .
      dockerfile: wasm.dockerfile
    networks:
      - truebit-net
    env_file:
      - .env

  sample_tasks:
    build:
      context: .
      dockerfile: samples-legacy.dockerfile

networks:
  truebit-net:
    driver: bridge